name: "tech-debt-checker"
description: "Check for tech-debts created/removed"
inputs:
  repo-token:
    description: "Github token secret"
    required: true
  strict:
    description: "Should block pr if threshold not pass?"
  threshold:
    description: "Maximum number of new tech-debts that can be added"
    default: "0"
runs:
  using: "node16"
  main: "dist/index.js"
